# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcode',
            name='create_time',
            field=models.CharField(max_length=300),
        ),
    ]
