# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20170102_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='create_time',
            field=models.FloatField(),
        ),
    ]
