# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20170102_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='random_code',
            field=models.CharField(max_length=50),
        ),
    ]
